# Generated by Django 5.1.2 on 2024-11-06 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('IdPago', models.AutoField(primary_key=True, serialize=False)),
                ('MetodoPago', models.CharField(max_length=20)),
                ('MontoPago', models.IntegerField()),
                ('FechaPago', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IdProducto', models.AutoField(primary_key=True, serialize=False)),
                ('NomProducto', models.CharField(max_length=30)),
                ('DescripcionProducto', models.TextField()),
                ('PrecioProducto', models.IntegerField()),
                ('StockProducto', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=30)),
                ('EmailUsuario', models.EmailField(max_length=254)),
                ('DireccionUsuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('IdCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.IntegerField()),
                ('ListaProducto', models.ManyToManyField(to='APIbackend.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('IdOrden', models.AutoField(primary_key=True, serialize=False)),
                ('FechaOrden', models.DateField(max_length=10)),
                ('EstadoOrden', models.CharField(max_length=30)),
                ('TotalOrden', models.IntegerField()),
                ('ProductOrden', models.ManyToManyField(to='APIbackend.producto')),
                ('UsuarioOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIbackend.usuario')),
            ],
        ),
    ]
