# Generated by Django 5.1.1 on 2024-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0002_usuarioapp_carrito_usuariocarrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioapp',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioapp',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioapp',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
