# Generated by Django 5.1.1 on 2024-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0003_alter_usuarioapp_apellido_alter_usuarioapp_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioapp',
            name='apellido',
            field=models.CharField(default=1000, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarioapp',
            name='nombre',
            field=models.CharField(default=1000, max_length=30),
            preserve_default=False,
        ),
    ]
