# Generated by Django 5.1.1 on 2024-11-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0004_alter_usuarioapp_apellido_alter_usuarioapp_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioapp',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioapp',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
