# Generated by Django 5.1.3 on 2024-11-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0007_alter_producto_categoriaproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PrecioOtroMetodo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='PrecioTransferencia',
            field=models.IntegerField(),
        ),
    ]
