# Generated by Django 5.1.3 on 2025-10-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0012_categoria_tipoproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='desuso_categoria_producto',
        ),
    ]
