# Generated by Django 5.1.3 on 2025-11-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0013_remove_producto_desuso_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='watts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
