# Generated by Django 5.2.8 on 2025-11-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0014_producto_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
    ]
