# Generated by Django 5.2.8 on 2025-11-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0015_producto_es_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
