# Generated by Django 5.2.8 on 2025-11-14 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0016_producto_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='usuario_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
