# Generated by Django 5.2.8 on 2025-12-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0019_seed_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'permissions': [('puede_editar_ordenes', 'Puede editar órdenes de clientes')]},
        ),
    ]
