# Generated by Django 5.2.8 on 2025-12-06 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0020_alter_orden_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
