# Generated by Django 5.2.8 on 2025-12-06 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0021_alter_orden_fecha_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
